function [torque_row,RPM_row] = EngineExcel2Vector(filename)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\mur\Documents\MATLAB\KTM_Export.xlsx
%    Worksheet: DataSheet
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/12 14:41:49



%% Import the data
[num] = xlsread(filename,'DataSheet');

%% Allocate imported array to column variable names
RPM = num(:,1);
torque = num(:,2);
torque_row=torque';
RPM_row = RPM';
%% Clear temporary variables
clearvars data raw;
